export const PROTOCOL_CONSTANTS = {
  NAME: "NEXORA",
  VERSION: "1.0.0",
  DEFAULT_NETWORK: "DEVNET" as const,
  SUPPORTED_NETWORKS: ["PAPER_TRADING", "DEVNET", "MAINNET"] as const,
  QUOTE_MINTS: {
    USDC_MAINNET: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
    USDC_DEVNET: "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU",
    SOL_MINT: "So11111111111111111111111111111111111111112",
  },
  DEFAULT_LIMITS: {
    MAX_POSITION_PERCENT: 5.0,
    MAX_DAILY_LOSS_PERCENT: 3.0,
    MAX_TOKEN_EXPOSURE_PERCENT: 10.0,
    MAX_SLIPPAGE_BPS: 50, // 0.50%
    MAX_OPEN_POSITIONS: 3,
    MIN_LIQUIDITY_USD: 50000,
    MAX_TRANSACTION_VALUE_USD: 2500,
    SCORE_BUY_THRESHOLD: 75.0,
    SCORE_WATCH_THRESHOLD: 60.0,
    STOP_LOSS_DEFAULT_PCT: 3.0,
    TAKE_PROFIT_1_PCT: 6.0,
    TAKE_PROFIT_2_PCT: 12.0,
    TRAILING_STOP_TRIGGER_PCT: 4.0,
    TRAILING_STOP_DISTANCE_PCT: 2.0,
    MAX_HOLD_TIME_MINUTES: 45,
    LOSS_COOLDOWN_MINUTES: 15,
    EXIT_COOLDOWN_MINUTES: 5,
  },
} as const;

export const REJECTION_REASONS = {
  RISK_POSITION_TOO_LARGE: "RISK_POSITION_TOO_LARGE",
  RISK_DAILY_LOSS_LIMIT: "RISK_DAILY_LOSS_LIMIT",
  RISK_LOW_LIQUIDITY: "RISK_LOW_LIQUIDITY",
  RISK_HIGH_SLIPPAGE: "RISK_HIGH_SLIPPAGE",
  RISK_HIGH_VOLATILITY: "RISK_HIGH_VOLATILITY",
  RISK_TOKEN_UNSAFE: "RISK_TOKEN_UNSAFE",
  RISK_MAX_EXPOSURE_REACHED: "RISK_MAX_EXPOSURE_REACHED",
  RISK_MAX_OPEN_POSITIONS: "RISK_MAX_OPEN_POSITIONS",
  RISK_SIMULATION_FAILED: "RISK_SIMULATION_FAILED",
  RISK_KILL_SWITCH_ACTIVE: "RISK_KILL_SWITCH_ACTIVE",
  RISK_COOLDOWN_ACTIVE: "RISK_COOLDOWN_ACTIVE",
  RISK_POLICY_DISABLED: "RISK_POLICY_DISABLED",
} as const;

export type RejectionReasonCode = keyof typeof REJECTION_REASONS;
